## Introduction

In this project, we are looking at different methods of regression, which are ridge, lasso, principal components, partial least squares, and ordinary least squares. Ridge and lasso regression are shrinkage methods and principal components and partial least squares are reduction methods. The purpose of comparing the different types of methods is so we can improve the linear model in our studies. Using other methods can allow for more prediction accuracy and model interpertability. 

Ordinary least squares is most effective when the number of observations is much larger than the number of variables in the model. This is because when there are many samples, the variance will be closer to the true variance by the law of large numbers. When variance is low, we will have a more accurate prediction when using the model. However, when our sample size is not significantly larger than the number of variables in our model, variance becomes a problem because that means our predictions from the model may be all over the place and we may have overfit our model. Another huge problem is that if the sample size is less than the number of variables we have in the model then we cannot use the ordinary least squares method because then our variance will be infinite. By using other methods, we are able to increase prediction accuracy in these scenarios.

We also want to use different methods because in some models, some variables are not correlated with the response variable. using ordinary least squares, we will leave those variables in the model, which can cause things to become more complicated. Using other models will set the coefficent of those uncorrelated variables to zero and when doing our analysis, the process will be easier because there will be less variables to interpert and the model will be easier to understand because we know that each the variables in the model have some significance. 

This is why we want to look into different methods such as ridge, lasso, principal component, and partial least squares. Thesse methods all bring some value to our model, but in different ways. So, we want to compare all of them with each other and see how the model produced using each method differs from one another. 