## Data

In this report, we are using data that originated from Credit.csv. In this data set, there are qualitative and quantative varaibles. The qualitiative variables are labeled as gender, student, status, and ethnicity. These variables are one's gender, if one is a student, if one is married, and one's ethnicity respectively. The quantiative variables in this are labeled as age, cards, education, income, limit, rating, and balance. These variables are one's age, the number of credit cards one has, years of education, income measured in thousands of dollars, credit limit, credit rating, and one's average credit card debt respectively.

Specifically, when doing out analysis, we are using a data set that we made from Credit.csv called scaled-credit.csv. In scaled-credit.csv, all of the variables are the same as those in Credit.csv. However, we converted factors (qualitative variables) into dummy variables, centered the mean, and standardized all of the data. Since, we standardized the data, this makes our data more comperable because all of our variables now have comparable scales. This is really important because our $\beta$ will be different depending on the scale that the variable is measured in. By centering and standardizing, we will not favor any coefficent. This is why we want to use the scaled-credit.csv instead of Credit.csv for our regression analysis. 